export const GET_POKEMON = 'GET_POKEMON';
export const GET_POKEMON__SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON__FAILURE = 'GET_POKEMON_FAILURE';
export const GET_POKEMON__ALREADY_EXIST = 'GET_POKEMON_ALREADY_EXIST';